version: '3.6'
services:
  db:
    image: bitnami/mongodb
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "{ ping: 1 }"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MONGODB_USERNAME=username
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=nodejs-example

  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    ports:
      - 9090:9090
    volumes: 
      - "./prometheus-data:/prometheus-data"
    command: 
      - "--web.enable-lifecycle" 
      - "--config.file=/prometheus-data/prometheus.yml"
